sudo: required

language: java
jdk:
  - openjdk11
node_js: "16.10.0"

services:
  - docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    cd webapp/;
    mvn -B -q -Pprod -DskipTests package docker:build;
    docker tag microcks/microcks quay.io/microcks/microcks:master;
    docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io;
    docker push quay.io/microcks/microcks:master;
    cd ../minions/async/;
    mvn -B -q -DskipTests package;
    docker build -f src/main/docker/Dockerfile.jvm -t quay.io/microcks/microcks-async-minion:master .;
    docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io;
    docker push quay.io/microcks/microcks-async-minion:latest;
    fi
  - if [ "$TRAVIS_BRANCH" == "1.5.x" ]; then
    cd webapp/;
    mvn -B -q -Pprod -DskipTests package docker:build;
    docker tag microcks/microcks quay.io/microcks/microcks:nightly;
    docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io;
    docker push quay.io/microcks/microcks:nightly;
    cd ../minions/async/;
    mvn -B -q -DskipTests package;
    docker build -f src/main/docker/Dockerfile.jvm -t quay.io/microcks/microcks-async-minion:nightly .;
    docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io;
    docker push quay.io/microcks/microcks-async-minion:nightly;
    fi
  - if [ "$TRAVIS_BRANCH" == "$TRAVIS_TAG" ]; then
    cd webapp/;
    mvn -B -q -Pprod -DskipTests package docker:build;
    docker tag microcks/microcks quay.io/microcks/microcks:$TRAVIS_TAG;
    docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io;
    docker push quay.io/microcks/microcks:$TRAVIS_TAG;
    cd ../minions/async/;
    mvn -B -q -DskipTests package;
    docker build -f src/main/docker/Dockerfile.jvm -t quay.io/microcks/microcks-async-minion:$TRAVIS_TAG .;
    docker login -u "$QUAY_USERNAME" -p "$QUAY_PASSWORD" quay.io;
    docker push quay.io/microcks/microcks-async-minion:$TRAVIS_TAG;
    fi
