name: Build and verify
on:
  push:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
  pull_request:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64

      - name: Build Java components
        run: mvn -B -q clean install

      - name: Build Angular app
        run: |
          set -x
          cd ${{github.workspace}}/webapp
          mvn -B -q -Pprod -DskipTests package

      - name: Check Javadoc completion
        run: mvn javadoc:javadoc


